### ISSUE TITLE
ToDo: Update cmake to use submodules

### ISSUE THREAD

**Issue by Ni1kko** [Ni1kko/extDB4#1]
Update CMakeLists.txt to include required submodules

- [ ] [boost](https://github.com/boostorg/boost/tree/9f93cd0ad4725d0641ce9e5017288698fdf4b9be)
- [ ] [mariadb](https://github.com/mariadb-corporation/mariadb-connector-c/tree/395641549ac72bc31def6d8b64e09093336aef72)
- [ ] [tbb4](https://github.com/BohemiaInteractive/TBB4/tree/b3f15c834d39da33b332c60672af95a1e68d9aa0)
